services:

    training-pipeline:
      build:
        context: .
        dockerfile: src/Dockerfile
#This is bind volume, different to shared named volume 
#Bind volume is like a portal or window which reaches out to the folders on the machine 
#Shared named volume is when we copy the folders into the docker internal drive
#Suitable for: * Bind Mounts: Use these during Development because you need to touch and see the files (like your CSVs and code) constantly.
#Named Volumes: Use these in Production (on a server) because they are faster and safer; you don't need to see the files, you just need Docker to remember them if the power goes out.
      volumes:
        - ./database:/app/database
        - ./mlruns:/app/mlruns
        - ./data:/app/data
# Links the host machine to the container's cache to save heavy model weights and skip re-downloads.
        - ./model_cache:/root/.cache
      environment:
        - MLFLOW_TRACKING_URI=sqlite:////app/database/mlflow.db
        - TABPFN_MODEL_CACHE_DIR=/root/.cache/tabpfn
# hugging face token
        - HF_TOKEN=your_token_here

    flask-service:
      build:
        context: .
        dockerfile: src/app/Dockerfile
      ports:
        - "5050:5050"
      volumes:
# Link the local Windows database folder to the container's /app/database folder so they share the same live data. Works like portal
        - ./database:/app/database
        - ./mlruns:/app/mlruns
        - ./model_cache:/root/.cache 
      environment:
# Overrides the env in the folder 
        - MLFLOW_TRACKING_URI=sqlite:////app/database/mlflow.db
        - MODEL_VERSION=production  
        - TABPFN_MODEL_CACHE_DIR=/root/.cache/tabpfn
        - HF_TOKEN=your_token_here
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
          interval: 5s
          timeout: 3s
          retries: 20